### ISSUE TITLE
Updating to 1.0.0 breaks AAI small iron poles

### ISSUE THREAD

**Issue by MrLenin** [0n0w1c/electric-grid#1]
Updated to 1.0.0 and all small iron electric poles from AAI stopped supplying power to equipment, small wood poles continue to work.
Downgraded to 0.4.4 and they work again.

**Comment by 0n0w1c** [comment]
Thank you very much for the report. Version 1.0.1 has been uploaded.

**Comment by MrLenin** [comment]
Awesome, fixed it. Thank you.
