### ISSUE TITLE
Multiplayer compatibility.

### ISSUE THREAD

**Issue by mindcloud69** [0n0w1c/electric-grid#2]
v 1.1.3

Unable to join dedicated server with your mod. 
 

647.924 Error ClientMultiplayerManager.cpp:1092: mod-electric-grid was not registered for the following nth_ticks when the map was saved but has registered them as a result of loading: 1
  647.924 Error ClientMultiplayerManager.cpp:85: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-electric-grid" + "

See link for possible explanation. Old but looks relevant. 
https://forums.factorio.com/viewtopic.php?t=107807

**Comment by 0n0w1c** [comment]
Thank you very much for the report and link.
Hmm, now what to do about it...
Looks like my allowing the change of the on_nth_tick() interval is a no-no for multiplayer.
I will do some investigation and attempt to resolve this.

**Comment by MrLenin** [comment]
I also just ran into this now while attempting to convert my single player game to multiplayer, happy to see it's already being looked into.

**Comment by 0n0w1c** [comment]
Any information as how I might reproduce this error?

**Comment by mindcloud69** [comment]
Sure basically just setup a multiplayer session. I setup a dedicated server on Linux but I am pretty sure that does not matter and the error should happen with any multiplayer setup. The error occurs as soon as you try to connect to the server. This was from my client log. 

Also FYI I actually got the error from two mods yours and mod-filter-combinator-improved

**Comment by mindcloud69** [comment]
Let me know if you need help with a server.

**Comment by 0n0w1c** [comment]
I am now setup with a LAN game and was able to recreate the error, thank you!

**Comment by 0n0w1c** [comment]
Version 1.1.4 has been uploaded, I believe this version resolves the issue.

**Comment by MrLenin** [comment]
Seems to have resolved it for me, will let you know if I notice any other problems.
