### ISSUE TITLE
Huge electric pole with AAI (Suggestion/Not a bug) 

### ISSUE THREAD

**Issue by MrLenin** [0n0w1c/electric-grid#3]
The Huge electric pole could probably better integrate with AAI if the recipe was tweaked to either require one Big electric pole with perhaps a ~1/3rd drop in the other input resources, or some amount concrete and swapping the copper plates for copper cable. The Big electric pole costs 5 steel plate, 8 iron sticks, 10 copper cable, and 1 concrete to craft with AAI. It's mostly notable as concrete must be crafted in an assembler, so it's easier to craft Huge poles than Big poles by hand, but it also easier to automate as well.

**Comment by 0n0w1c** [comment]
Thank you, much appreciated. I have modified the recipe and uploaded version 1.2.1.
